name = "dm3-opname-gateway"
#account_id = "15dcc9085cb794bb4f29d3e8177ac880"
main = "./src/worker.ts"
node_compat = true
compatibility_date = "2023-10-13"

[dev]
port = 8080

[build]
command = "yarn build"

[vars]
L1_PROVIDER_URL = ''
L2_PROVIDER_URL = ''
L2_OUTPUT_ORACLE = '0xdfe97868233d1aa22e815a266982f2cf17685a27'
DELAY =0
